# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '3-3 kiosk.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QMenuBar, QPushButton, QSizePolicy,
    QStackedWidget, QStatusBar, QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1009, 764)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 30, 951, 511))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.tabWidget = QTabWidget(self.page)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 901, 481))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.West)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tabWidget.setElideMode(Qt.TextElideMode.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(130, 130, 61, 21))
        self.menuButton1 = QPushButton(self.tab)
        self.menuButton1.setObjectName(u"menuButton1")
        self.menuButton1.setGeometry(QRect(80, 40, 161, 71))
        self.menuButton2 = QPushButton(self.tab)
        self.menuButton2.setObjectName(u"menuButton2")
        self.menuButton2.setGeometry(QRect(300, 40, 161, 71))
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(350, 130, 61, 21))
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(130, 160, 61, 21))
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 160, 61, 21))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.menuButton3 = QPushButton(self.tab_2)
        self.menuButton3.setObjectName(u"menuButton3")
        self.menuButton3.setGeometry(QRect(80, 40, 161, 71))
        self.label_5 = QLabel(self.tab_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(130, 160, 61, 21))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 130, 61, 21))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(350, 130, 61, 21))
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(350, 160, 61, 21))
        self.menuButton4 = QPushButton(self.tab_2)
        self.menuButton4.setObjectName(u"menuButton4")
        self.menuButton4.setGeometry(QRect(300, 40, 161, 71))
        self.tabWidget.addTab(self.tab_2, "")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.hereButton = QPushButton(self.page_3)
        self.hereButton.setObjectName(u"hereButton")
        self.hereButton.setGeometry(QRect(300, 160, 151, 131))
        self.togoButton = QPushButton(self.page_3)
        self.togoButton.setObjectName(u"togoButton")
        self.togoButton.setGeometry(QRect(540, 160, 151, 131))
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.cardButton = QPushButton(self.page_2)
        self.cardButton.setObjectName(u"cardButton")
        self.cardButton.setGeometry(QRect(160, 160, 151, 131))
        self.cashButton = QPushButton(self.page_2)
        self.cashButton.setObjectName(u"cashButton")
        self.cashButton.setEnabled(True)
        self.cashButton.setGeometry(QRect(400, 160, 151, 131))
        self.cashButton.setCheckable(False)
        self.cashButton.setFlat(False)
        self.qrButton = QPushButton(self.page_2)
        self.qrButton.setObjectName(u"qrButton")
        self.qrButton.setGeometry(QRect(630, 160, 151, 131))
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.label_10 = QLabel(self.page_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(390, 200, 191, 51))
        font = QFont()
        font.setPointSize(28)
        self.label_10.setFont(font)
        self.stackedWidget.addWidget(self.page_4)
        self.listWidget = QListWidget(self.centralwidget)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(50, 540, 581, 141))
        self.payButton = QPushButton(self.centralwidget)
        self.payButton.setObjectName(u"payButton")
        self.payButton.setGeometry(QRect(830, 590, 101, 91))
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(700, 620, 111, 51))
        font1 = QFont()
        font1.setPointSize(18)
        self.label_9.setFont(font1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1009, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\uc544\uba54\ub9ac\uce74\ub178", None))
        self.menuButton1.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.menuButton2.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\uce74\ud398\ub77c\ub5bc", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"2,500\uc6d0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"3,000\uc6d0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"\uc74c\ub8cc", None))
        self.menuButton3.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"2,000\uc6d0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"\uac10\uc790\uce69", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"\ud325\ube59\uc218", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"6,000\uc6d0", None))
        self.menuButton4.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"\uac04\uc2dd", None))
        self.hereButton.setText(QCoreApplication.translate("MainWindow", u"\uba39\uace0\uac00\uae30", None))
        self.togoButton.setText(QCoreApplication.translate("MainWindow", u"\ud3ec\uc7a5\ud558\uae30", None))
        self.cardButton.setText(QCoreApplication.translate("MainWindow", u"\uce74\ub4dc", None))
        self.cashButton.setText(QCoreApplication.translate("MainWindow", u"\ud604\uae08", None))
        self.qrButton.setText(QCoreApplication.translate("MainWindow", u"\ud398\uc774", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"\uac10\uc0ac\ud569\ub2c8\ub2e4", None))
        self.payButton.setText(QCoreApplication.translate("MainWindow", u"\uacb0\uc81c\ud558\uae30", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"30,000 \uc6d0", None))
    # retranslateUi

